// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EasyNote.Models;

public partial class Calendar
{
    public string UserId { get; set; }

    public string EventId { get; set; }

    public string EventName { get; set; }

    public string EventContent { get; set; }

    public DateTime EventStartTime { get; set; }

    public DateTime EventEndTime { get; set; }

    public DateTime CreateDate { get; set; }
}