// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EasyNote.Models;

public partial class Note
{
    public string UserId { get; set; }

    public string NoteId { get; set; }

    public string NoteName { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LastEditDate { get; set; }
}