// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EasyNote.Models;

public partial class User
{
    public string Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public DateTime CreateDate { get; set; }

    public byte[] ProfileImage { get; set; }

    public string RegistType { get; set; }
}